language: go

go:
  - tip
  - 1.8

install:
  - go get -t ./...
  - go get github.com/mholt/caddy/caddyhttp
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/golang/lint/golint

script:
  - sed -i 's/\_ \"github.com\/mholt\/caddy\/caddyhttp\"/\_ \"github.com\/mholt\/caddy\/caddyhttp\"\n\_ \"github.com\/hacdias\/caddy-hugo\"/g' $GOPATH/src/github.com/mholt/caddy/caddy/caddymain/run.go
  - go build github.com/mholt/caddy/caddy
  - diff <(echo -n) <(gofmt -s -d .)
  - ineffassign .
  - misspell -error .
  - go vet ./...
  - go test -race ./...

after_script:
  - golint ./...